# Generated by Django 4.0.6 on 2022-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_count', models.IntegerField(null=True)),
                ('max_try', models.IntegerField(null=True)),
                ('tried_chars', models.CharField(max_length=50, null=True)),
                ('word', models.CharField(max_length=50, null=True)),
                ('hidden', models.CharField(max_length=50, null=True)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
