# Generated by Django 4.0.6 on 2022-07-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hangman',
            new_name='Hangman_Game',
        ),
        migrations.RenameField(
            model_name='hangman_game',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='hangman_game',
            old_name='hidden',
            new_name='hidden_chars',
        ),
        migrations.RenameField(
            model_name='hangman_game',
            old_name='tried_chars',
            new_name='try_chars',
        ),
    ]
