# Generated by Django 4.0.5 on 2022-07-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangman',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='false',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='hidden',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hangman',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
