# Generated by Django 4.0.5 on 2022-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_remove_hangman_answer_remove_hangman_chance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangman',
            name='ans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='false',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='hidden',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hangman',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
