# Generated by Django 4.0.5 on 2022-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_hangman_ans_hangman_answer_hangman_chance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangman',
            old_name='chance',
            new_name='max_try',
        ),
        migrations.RenameField(
            model_name='hangman',
            old_name='false',
            new_name='tried_chars',
        ),
        migrations.RenameField(
            model_name='hangman',
            old_name='answer',
            new_name='word',
        ),
        migrations.AddField(
            model_name='hangman',
            name='try_count',
            field=models.IntegerField(null=True),
        ),
    ]
