# Generated by Django 4.0.5 on 2022-07-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_rename_chance_hangman_max_try_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangman',
            name='point',
        ),
        migrations.AlterField(
            model_name='hangman',
            name='ans',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hangman',
            name='tried_chars',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
