# Generated by Django 4.0.5 on 2022-07-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_remove_hangman_point_alter_hangman_ans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman',
            name='ans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hangman',
            name='tried_chars',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
